// Generated by CoffeeScript 1.7.1
(function() {
  var NormalEnemy,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  window.NormalEnemy = NormalEnemy = (function(_super) {
    __extends(NormalEnemy, _super);

    function NormalEnemy(position) {
      NormalEnemy.__super__.constructor.call(this, position, $V([70, 70]));
      this.wave = new Wave(0.05);
      this.desiredVelocity = $V([-5, 0]);
      this.multiplyFactor = 0.1;
    }

    NormalEnemy.prototype.update = function(state) {
      this.velocity = this.velocity.add(this.desiredVelocity.subtract(this.velocity).multiply(this.multiplyFactor));
      NormalEnemy.__super__.update.call(this, state);
      if (this.position.e(1) < 0) {
        return state.removeLater("enemies", this);
      }
    };

    return NormalEnemy;

  })(GameObject);

}).call(this);
