// Generated by CoffeeScript 1.7.1
(function() {
  var NormalEnemy,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  window.NormalEnemy = NormalEnemy = (function(_super) {
    __extends(NormalEnemy, _super);

    function NormalEnemy(position) {
      NormalEnemy.__super__.constructor.call(this, position, $V([70, 70]));
      this.wave = new Wave(0.1);
    }

    return NormalEnemy;

  })(GameObject);

}).call(this);
