// Generated by CoffeeScript 1.7.1
(function() {
  var GameObject;

  window.GameObject = GameObject = (function() {
    GameObject.showHitboxes = true;

    function GameObject(position, size, velocity, rotation) {
      this.position = position;
      this.size = size;
      this.velocity = velocity != null ? velocity : $V([0, 0]);
      this.rotation = rotation != null ? rotation : 0;
    }

    GameObject.prototype.update = function() {
      return this.position = this.position.add(this.velocity);
    };

    GameObject.prototype.draw = function(ctx) {
      ctx.save();
      if (GameObject.showHitboxes) {
        ctx.fillStyle = 'rgb(200,0,0)';
        ctx.rotate(this.rotation);
        ctx.fillRect(this.position.e(1), this.position.e(2), this.size.e(1), this.size.e(2));
      }
      return ctx.restore();
    };

    return GameObject;

  })();

}).call(this);
