// Generated by CoffeeScript 1.7.1
(function() {
  window.myTest = function() {
    var canvas, ctx, draw, state, update;
    state = new State();
    canvas = document.getElementById('game');
    ctx = canvas.getContext('2d');
    update = function() {
      return state.update();
    };
    draw = function(ctx) {
      ctx.clearRect(0, 0, 400, 400);
      return state.draw(ctx);
    };
    return setInterval(function() {
      update();
      return draw(ctx);
    }, 1000 / 30);
  };

}).call(this);
