// Generated by CoffeeScript 1.7.1
(function() {
  var Player,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  window.Player = Player = (function(_super) {
    __extends(Player, _super);

    function Player(position) {
      Player.__super__.constructor.call(this, position, $V([100, 100]));
    }

    Player.prototype.update = function() {
      if (kd.W.isDown()) {
        this.position = this.position.add([0, -1]);
      }
      if (kd.S.isDown()) {
        this.position = this.position.add([0, 1]);
      }
      if (kd.A.isDown()) {
        this.position = this.position.add([-1, 0]);
      }
      if (kd.D.isDown()) {
        return this.position = this.position.add([1, 0]);
      }
    };

    return Player;

  })(GameObject);

}).call(this);
