// Generated by CoffeeScript 1.7.1
(function() {
  var Player,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  window.Player = Player = (function(_super) {
    __extends(Player, _super);

    function Player(position) {
      Player.__super__.constructor.call(this, position, $V([100, 100]));
    }

    return Player;

  })(GameObject);

}).call(this);
