// Generated by CoffeeScript 1.7.1
(function() {
  var State;

  window.State = State = (function() {
    function State() {
      this.objects = this.initializeObjects();
    }

    State.prototype.initializeObjects = function() {
      var center;
      center = $V([200, 200]);
      return _.chain([new Player(center)]).union(this.initializeEnemies(center)).union(this.testParticles(center)).value();
    };

    State.prototype.initializeEnemies = function(center) {
      return _([1, 2, 3, 4, 5]).map(function(i) {
        var offset;
        offset = $V([(Math.random() * 2) - 1, (Math.random() * 2) - 1]);
        return new NormalEnemy(center.add(offset.multiply(100)));
      });
    };

    State.prototype.testParticles = function(center) {
      var _i, _results;
      return _((function() {
        _results = [];
        for (_i = 1; _i <= 100; _i++){ _results.push(_i); }
        return _results;
      }).apply(this)).map(function(i) {
        var offset;
        offset = $V([(Math.random() * 2) - 1, (Math.random() * 2) - 1]);
        return new Particle(center.add(offset.multiply(50)), $V([10, 10]), $V([Math.random(), Math.random()]).multiply(2), 'rgb(200, 0, 0)');
      });
    };

    State.prototype.update = function() {
      var obj, _i, _len, _ref, _results;
      _ref = this.objects;
      _results = [];
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        obj = _ref[_i];
        _results.push(obj.update());
      }
      return _results;
    };

    State.prototype.draw = function(ctx) {
      var obj, _i, _len, _ref, _results;
      _ref = this.objects;
      _results = [];
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        obj = _ref[_i];
        ctx.save();
        obj.draw(ctx);
        _results.push(ctx.restore());
      }
      return _results;
    };

    return State;

  })();

}).call(this);
