// Generated by CoffeeScript 1.7.1
(function() {
  var State;

  window.State = State = (function() {
    function State() {
      this.objects = [];
    }

    State.prototype.update = function() {
      return _(this.objects).each(function(obj) {
        return obj.update();
      });
    };

    State.prototype.draw = function(ctx) {
      return _(this.objects).each(function(obj) {
        return obj.draw(ctx);
      });
    };

    return State;

  })();

}).call(this);
